# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(717, 481)
        MainWindow.setMinimumSize(QtCore.QSize(717, 481))
        MainWindow.setMaximumSize(QtCore.QSize(717, 481))
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(15, 50, 141, 301))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.Button_Open = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.Button_Open.setFont(font)
        self.Button_Open.setIconSize(QtCore.QSize(20, 40))
        self.Button_Open.setObjectName("Button_Open")
        self.gridLayout.addWidget(self.Button_Open, 1, 0, 1, 2)
        self.Button_FindPort = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.Button_FindPort.setFont(font)
        self.Button_FindPort.setObjectName("Button_FindPort")
        self.gridLayout.addWidget(self.Button_FindPort, 2, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 42, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 2)
        self.Box_get_port = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.Box_get_port.setFont(font)
        self.Box_get_port.setIconSize(QtCore.QSize(30, 20))
        self.Box_get_port.setObjectName("Box_get_port")
        self.gridLayout.addWidget(self.Box_get_port, 0, 1, 1, 1)
        self.Button_Getfile = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.Button_Getfile.setFont(font)
        self.Button_Getfile.setObjectName("Button_Getfile")
        self.gridLayout.addWidget(self.Button_Getfile, 5, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.Button_Clear = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.Button_Clear.setFont(font)
        self.Button_Clear.setObjectName("Button_Clear")
        self.gridLayout.addWidget(self.Button_Clear, 4, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(21, 30, 72, 20))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(21, 205, 72, 20))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(91, 40, 72, 3))
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(163, 40, 3, 145))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(5, 40, 3, 146))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(6, 40, 15, 3))
        self.line_4.setLineWidth(1)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(5, 185, 159, 3))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(91, 218, 73, 3))
        self.line_6.setLineWidth(1)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(6, 218, 15, 3))
        self.line_7.setLineWidth(1)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(5, 218, 3, 110))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(163, 218, 3, 108))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(5, 325, 159, 3))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(534, 60, 171, 298))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.formLayoutWidget.setFont(font)
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_temp = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_temp.setFont(font)
        self.label_temp.setObjectName("label_temp")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_temp)
        self.label_humidity = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_humidity.setFont(font)
        self.label_humidity.setObjectName("label_humidity")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_humidity)
        self.label_speed = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_speed.setFont(font)
        self.label_speed.setObjectName("label_speed")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_speed)
        self.label_dierction = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_dierction.setFont(font)
        self.label_dierction.setObjectName("label_dierction")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_dierction)
        self.label_pressure = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_pressure.setFont(font)
        self.label_pressure.setObjectName("label_pressure")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.label_pressure)
        spacerItem2 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.SpanningRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.SpanningRole, spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.SpanningRole, spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.SpanningRole, spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.SpanningRole, spacerItem6)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.label_9)
        self.label_time = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_time.setObjectName("label_time")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.label_time)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(196, 11, 91, 20))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(541, 30, 101, 21))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(285, 20, 237, 3))
        self.line_11.setLineWidth(1)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(173, 20, 20, 3))
        self.line_12.setLineWidth(1)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(173, 20, 3, 382))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(173, 400, 349, 3))
        self.line_14.setLineWidth(1)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(522, 20, 3, 381))
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setGeometry(QtCore.QRect(631, 40, 79, 3))
        self.line_16.setLineWidth(1)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.line_17 = QtWidgets.QFrame(self.centralwidget)
        self.line_17.setGeometry(QtCore.QRect(528, 40, 12, 3))
        self.line_17.setLineWidth(1)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.line_18 = QtWidgets.QFrame(self.centralwidget)
        self.line_18.setGeometry(QtCore.QRect(528, 40, 3, 321))
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.line_19 = QtWidgets.QFrame(self.centralwidget)
        self.line_19.setGeometry(QtCore.QRect(528, 360, 182, 3))
        self.line_19.setLineWidth(1)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.line_20 = QtWidgets.QFrame(self.centralwidget)
        self.line_20.setGeometry(QtCore.QRect(710, 40, 3, 321))
        self.line_20.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(10, 350, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.Button_exit = QtWidgets.QPushButton(self.centralwidget)
        self.Button_exit.setGeometry(QtCore.QRect(635, 370, 71, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.Button_exit.setFont(font)
        self.Button_exit.setObjectName("Button_exit")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(178, 36, 341, 361))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 717, 26))
        self.menuBar.setObjectName("menuBar")
        self.menufile = QtWidgets.QMenu(self.menuBar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.display_Temp = QtWidgets.QAction(MainWindow)
        self.display_Temp.setObjectName("display_Temp")
        self.display_Humidity = QtWidgets.QAction(MainWindow)
        self.display_Humidity.setObjectName("display_Humidity")
        self.display_speed = QtWidgets.QAction(MainWindow)
        self.display_speed.setObjectName("display_speed")
        self.display_Direction = QtWidgets.QAction(MainWindow)
        self.display_Direction.setObjectName("display_Direction")
        self.display_Pressure = QtWidgets.QAction(MainWindow)
        self.display_Pressure.setObjectName("display_Pressure")
        self.get_file_drew = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(10)
        self.get_file_drew.setFont(font)
        self.get_file_drew.setObjectName("get_file_drew")
        self.now_file_drew = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(10)
        self.now_file_drew.setFont(font)
        self.now_file_drew.setObjectName("now_file_drew")
        self.toolBar.addAction(self.display_Temp)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.display_Humidity)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.display_speed)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.display_Pressure)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.display_Direction)
        self.toolBar.addSeparator()
        self.menufile.addAction(self.now_file_drew)
        self.menufile.addSeparator()
        self.menufile.addAction(self.get_file_drew)
        self.menuBar.addAction(self.menufile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "自动气象站数据接收机"))
        self.Button_Open.setText(_translate("MainWindow", "打开"))
        self.Button_FindPort.setText(_translate("MainWindow", "检测串口"))
        self.Button_Getfile.setText(_translate("MainWindow", "获取文件"))
        self.label_2.setText(_translate("MainWindow", "串口号"))
        self.Button_Clear.setText(_translate("MainWindow", "清除接收"))
        self.label.setText(_translate("MainWindow", "选择串口"))
        self.label_3.setText(_translate("MainWindow", "接收设置"))
        self.label_4.setText(_translate("MainWindow", "温度(℃):"))
        self.label_5.setText(_translate("MainWindow", "湿度(RH%):"))
        self.label_6.setText(_translate("MainWindow", "风速(m/s):"))
        self.label_8.setText(_translate("MainWindow", "气压(hPa):"))
        self.label_7.setText(_translate("MainWindow", "风向:"))
        self.label_temp.setText(_translate("MainWindow", "25.5"))
        self.label_humidity.setText(_translate("MainWindow", "56.7"))
        self.label_speed.setText(_translate("MainWindow", "3.22"))
        self.label_dierction.setText(_translate("MainWindow", "西北"))
        self.label_pressure.setText(_translate("MainWindow", "1015.2"))
        self.label_9.setText(_translate("MainWindow", "检测时间:"))
        self.label_time.setText(_translate("MainWindow", "2020/05/12 16:15:13"))
        self.label_14.setText(_translate("MainWindow", "数据接收区"))
        self.label_15.setText(_translate("MainWindow", "气象观测值"))
        self.label_16.setText(_translate("MainWindow", "CDIO - By Robin"))
        self.Button_exit.setText(_translate("MainWindow", "退出"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menufile.setTitle(_translate("MainWindow", "绘图选项"))
        self.display_Temp.setText(_translate("MainWindow", "温度图像"))
        self.display_Temp.setToolTip(_translate("MainWindow", "显示温度数据"))
        self.display_Humidity.setText(_translate("MainWindow", "湿度图像"))
        self.display_Humidity.setToolTip(_translate("MainWindow", "显示湿度数据"))
        self.display_speed.setText(_translate("MainWindow", "风速图像"))
        self.display_speed.setToolTip(_translate("MainWindow", "显示风速数据"))
        self.display_Direction.setText(_translate("MainWindow", "风向图像"))
        self.display_Direction.setToolTip(_translate("MainWindow", "显示风向数据"))
        self.display_Pressure.setText(_translate("MainWindow", "大气压图像"))
        self.display_Pressure.setToolTip(_translate("MainWindow", "显示大气压数据"))
        self.get_file_drew.setText(_translate("MainWindow", "选择文件绘图"))
        self.now_file_drew.setText(_translate("MainWindow", "实时数据绘图"))
